# Generated by Django 5.1.4 on 2025-01-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('short_description', models.CharField(max_length=600)),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
