# Generated by Django 5.1.4 on 2025-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_prize_alter_course_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('short_description', models.CharField(blank=True, max_length=600)),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('video_link', models.CharField(blank=True, max_length=300)),
                ('facebook', models.CharField(blank=True, max_length=300)),
                ('whatsapp', models.CharField(blank=True, max_length=300)),
                ('youtube', models.CharField(blank=True, max_length=300)),
                ('instagram', models.CharField(blank=True, max_length=300)),
                ('telegram', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
