# Generated by Django 5.1.4 on 2025-01-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=600)),
                ('description', models.TextField()),
                ('position', models.CharField(max_length=600)),
                ('status', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('subject', models.CharField(max_length=600)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.filial')),
            ],
        ),
    ]
