# Generated by Django 5.1.4 on 2025-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
            ],
        ),
    ]
