# Generated by Django 5.1.4 on 2025-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
