# Generated by Django 5.1.4 on 2025-01-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_filial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prize',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
